### ISSUE TITLE
Ground

### ISSUE THREAD

**Issue by M3gaFr3ak** [jersagfast/One-Square-Inch-of-Goodness#1]
The ground pins dont seem to have a connection:
http://puu.sh/aYcz3/bfd58a6618.png

**Comment by M3gaFr3ak** [comment]
Oh, seems like you used a ground plane :dancer: 
is there a reason eagle doesnt render it for me?

**Comment by jersagfast** [comment]
Yup, ground plane. Try running the rats nest function, it will then render the ground plane. 👍

**Comment by M3gaFr3ak** [comment]
thanks! was a bit shocked first because i ordered 3 pcbs on oshpark and thought i'd need to wirebridge now ^^
