### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by canihavesomecoffee** [jersagfast/One-Square-Inch-of-Goodness#2]
Hey,

I have no idea what kind of copyright you put on this board, but I'd like to point your attention to this kickstarter project, which seems to be a blatant clone of your board:

https://www.kickstarter.com/projects/597783004/arduino-smd-style/description

**Comment by jersagfast** [comment]
Thanks for the heads up Willem, that guy even used my pictures. Can I offer you a free one for the favor? If so, just send me your address, I’ll cover shipping.

Jeremy Saglimbeni
jeremy@thecustomgeek.com
http://thecustomgeek.com

**Comment by canihavesomecoffee** [comment]
Hello,

I have sent you an email (to jeremy@...) about the address :+1:
